name: Unit Tests

on:
  push:
    branches: [ "main" ]

  pull_request:
    branches: [ "**" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        cache: 'npm'
        
    - run: npm install
    - run: npm test
